### ISSUE TITLE
[question] CacheFactory values for expirity and TTL not working

### ISSUE THREAD

**Issue by nicky-lenaers** [ngx-cache/core#7]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the README and search github for a similar issue or PR before submitting
[ ] support request => check the README and search github for a similar issue or PR before submitting
[ ] feature request
```

**Current behavior**

When using the `cacheFactory()` and setting both `expirity` and `TTL` to `86400`, the cache is being removed from disk on app load (folder `.cache` remains, but without content). Code Snippet:

```ts
export function cacheFactory(): CacheLoader {
	return new CacheStaticLoader('NGX_CACHE', {
		"expiry": 86400,
		"TTL": 86400
	});
}
```

When setting both values to the default of `Number.MAX_VALUE`, it works, but I need a lower value than that.

**Expected/desired behavior**

Cache should remain for 1 day at least (60 * 60 * 24 = 86400).

**Minimal reproduction of the problem with instructions**

Apply above values to `expirity` and `TTL`. Rest of both client and server cache modules are implemented exactly according to the given documentation and README.

**What is the motivation / use case for changing the behavior?**

Causes errors at runtime.

**Please tell us about your environment:**

* **Angular version:** 2.0.X

4.2.3

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

 All

* **Language:** [all | TypeScript X.X | ES6/7 | ES5]
TypeScript

* **Node (for AoT issues):** `node --version` =   7.10

**Comment by fulls1z3** [comment]
@nicky-lenaers sorry for replying late, but have you ever try just setting **only the TTL**?

```typescript
export function cacheFactory(): CacheLoader {
	return new CacheStaticLoader('NGX_CACHE', {
		"TTL": 86400
	});
}
```
